---
pod:
  containerPort: 80
  imageName: "mcr.microsoft.com/dotnet/core/samples"
  imageTag: "aspnetapp"
  name: aspnetapp
  containerName: aspnetapp-image
  containerProtocol: TCP
  namespace: ingress
  tolerations:
    key: "nodepool03"
    operator: "Equal"
    value: "true"
    effect: "NoExecute"


service:
  name: aspnetapp
  targetPort: 80
  port: 80
  namespace: ingress

ingress:
  name: aspnetapp
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
  namespace: ingress