apiVersion: v1
kind: Pod
metadata:
  name: {{ .Values.pod.name }}
  namespace: {{ .Values.pod.namespace }}
  labels:
    app: {{ .Values.pod.name }}
spec:
  {{- if .Values.pod.tolerations }}
  tolerations:
  {{ toYaml .Values.pod.tolerations | indent 8 }}
  {{- end }}
  containers:
  - image: "{{ .Values.pod.imageName }}:{{ .Values.pod.imageTag }}"
    name: {{ .Values.pod.containerName }}
    ports:
    - containerPort: {{ .Values.pod.containerPort }}
      protocol: {{ .Values.pod.containerProtocol }}