apiVersion: v1
kind: Pod
metadata:
  name: {{ .Values.pod.name }}
  namespace: {{ .Values.pod.namespace }}
  labels:
    app: {{ .Values.pod.name }}
spec:
  tolerations:
  - key: "nodepool03"
    operator: "Equal"
    value: "true"
    effect: "NoExecute"
  containers:
  - image: "{{ .Values.pod.imageName }}:{{ .Values.pod.imageTag }}"
    name: {{ .Values.pod.containerName }}
    ports:
    - containerPort: {{ .Values.pod.containerPort }}
      protocol: {{ .Values.pod.containerProtocol }}