apiVersion: v1
kind: Pod
metadata:
  name: {{ .Values.pod.name }}
  namespace: {{ .Values.pod.namespace }}
  labels:
    app: {{ .Values.pod.name }}
spec:
  tolerations:
  - key: {{ .Values.pod.tolerations.key }}
    operator: {{ .Values.pod.tolerations.operator }}
    value: { .Values.pod.tolerations.value }}
    effect: { .Values.pod.tolerations.effect }}
  containers:
  - image: "{{ .Values.pod.imageName }}:{{ .Values.pod.imageTag }}"
    name: {{ .Values.pod.containerName }}
    ports:
    - containerPort: {{ .Values.pod.containerPort }}
      protocol: {{ .Values.pod.containerProtocol }}