apiVersion: v1
kind: Pod
metadata:
  name: {{ .Values.pod.name }}
  labels:
    app: {{ .Values.pod.name }}
spec:
  containers:
  - image: "{{ .Values.pod.imageName }}:{{ .Values.pod.imageTag }}"
    name: {{ .Values.pod.containerName }}
    ports:
    - containerPort: {{ .Values.pod.containerPort }}
      protocol: {{ .Values.pod.containerProtocol }}