apiVersion: v1
kind: Pod
metadata:
  name: {{ .Values.pod.name }}
  namespace: {{ .Values.pod.namespace }}
  labels:
    app: {{ .Values.pod.name }}
spec:
  {{- range .Values.pod.tolerations }}
  tolerations:
  -  key: {{ .key }}
     operator: {{ .operator }}
     value: {{ .value }}
     effect: {{ .effect }}
  {{- end }}
  containers:
  - image: "{{ .Values.pod.imageName }}:{{ .Values.pod.imageTag }}"
    name: {{ .Values.pod.containerName }}
    ports:
    - containerPort: {{ .Values.pod.containerPort }}
      protocol: {{ .Values.pod.containerProtocol }}